services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_TOKEN=${GIT_TOKEN}
    ports:
      - "8188:8188"
    volumes:
      - ./output:/comfyui/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
